language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t hjmartik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hjmartik/react-test npm test

after_success:
  - docker build -t hjmartik/multi-client ./client
  - docker build -t hjmartik/multi-nginx ./nginx
  - docker build -t hjmartik/multi-server ./server
  - docker build -t hjmartik/multi-worker ./worker
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hjmartik/multi-client
  - docker push hjmartik/multi-nginx
  - docker push hjmartik/multi-server
  - docker push hjmartik/multi-worker